language: node_js
sudo: false
node_js:
  - 5
env:
  - NODE_ENV="test"
before_script:
  - createuser sfmovies_user
  - createdb -O sfmovies_user sfmovies_test
  - npm run db:migrate
script:
  - npm run lint
  - npm test
  - npm run enforce
